# ARDUINO_DIR = /usr/share/arduino
BOARD_SUB=atmega2560
BOARD_TAG=mega
ARDUINO_DIR = $(HOME)/catkin_ws/src/mitra_ros/ArduinoCore-avr
ARDUINO_PORT = /dev/motorcontrol
ARDUINO_VAR_PATH = $(ARDUINO_DIR)/variants
BOARDS_TXT = $(ARDUINO_DIR)/boards.txt
ARDUINO_LIBS = Bolder_Flight_Systems_MPU9250 Wire SPI 
USER_LIB_PATH = $(ARDUINO_DIR)/libraries
ARDUINO_CORE_PATH = $(ARDUINO_DIR)/cores/arduino

include $(HOME)/catkin_ws/src/mitra_ros/Arduino-Makefile/Arduino.mk
